version: '3'
services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: postgres:9.6
    volumes:
      - mydata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Nyamwaro2012
      POSTGRES_USER: postgres
volumes:
  mydata: